name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 22.00 pm UTC or 06.00  UTC+8
    - cron: "0 22 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
          
      - name: Setup git
        run: |
          git config --local user.email "sniren2002@gmail.com"
          git config --local user.name "sniren210"

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"

      - name: Commit files
#         continue-on-error: true
        env:
          COMMIT_MESSAGE: "feat: update waka"
        run: git add . && git commit -m "${{ env.COMMIT_MESSAGE }}" -a
